### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### createa attach
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="fari.jpg"

< C:\Users\user\Downloads\fari.jpg

### open
GET localhost:8080/api/v1/attach/open/fari.jpg