### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Create article
GET localhost:8080/api/v1/article/create

### Create article
POST http://localhost:8080/api/v1/article/create
Content-Type: application/json

{
  "title": "jamshe",
  "description": "haaaaa",
  "content": "as",
  "regionId": "1",
  "imageId": "549",
  "categoryList": [1],
  "sectionList": [1]
}
