### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Create article
GET localhost:8080/api/v1/article/create

### Create article
POST localhost:8080/api/v1/article/create
Content-Type: application/json

{
  "title": "jamshet",
  "description": "whaaaaa",
  "content": "asd",
  "regionId": "1",
  "categoryList": []
}