### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### create profile
POST localhost:8080/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Baxtiyor",
  "surname": "Yusupov",
  "username": "yusupovv17@icloud.com",
  "password": "bb7"
}

### verification
GET http://localhost:8080/api/v1/auth/registration/verification/eyJhbGciOiJIUzM4NCJ9.eyJjb2RlIjoiNDEwNDQiLCJ1c2VybmFtZSI6Inl1c3Vwb3Z2MTdAaWNsb3VkLmNvbSIsInN1YiI6Inl1c3Vwb3Z2MTdAaWNsb3VkLmNvbSIsImlhdCI6MTc0ODg3Mzk0MiwiZXhwIjoxNzQ4ODc3NTQyfQ.CYtUyS7Z3jx8MFv_IJVeHhJ6cq2_DCAKNAnR8dESaIjPQkdnyr1ADf9DaHi3duWF

### login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "baxtiyorking17@gmail.com",
  "password": "parol123"
}