### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### create
POST localhost:8080/api/v1/category
Content-Type: application/json

{
  "orderNumber" : 101,
  "nameUz" : "Qarshyev",
  "nameRu" : "йфаыфа",
  "nameEn" : "Kharshiyiv",
  "key" : "qwerty12"

}

### Get by id
GET localhost:8080/api/v1/profile/9