### CREATE profile
POST http://localhost:8080/api/v1/profile/create
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Valiyyev",
  "phone": "+998901234567",
  "email": "ali@gmail.com",
  "password": "securePassword123",
  "status": "ACTIVE",
  "photoId": "photo123",
  "rolesEnumList": ["ADMIN", "MODERATOR"]
}

### GET profile by ID
GET http://localhost:8080/api/v1/profile/1
Accept: application/json

### UPDATE profile
PUT http://localhost:8080/api/v1/profile/1
Content-Type: application/json

{
  "name": "VAli",
  "surname": "aliyyev",
  "phone": "+998901234567",
  "email": "vali@gmail.com",
  "password": "Password123",
  "status": "NOT_ACTIVE",
  "photoId": "photo123",
  "rolesEnumList": ["PUBLISHER"]
}

### DELETE profile
DELETE http://localhost:8080/api/v1/profile/1
