### CREATE
POST http://localhost:8080/api/v1/region/create
Content-Type: application/json

{
  "orderNumber": 3,
  "nameUz": "Urganch",
  "nameRu": "Ташкент",
  "nameEn": "Tashkent",
  "key": "tashkent",
  "visible": true
}


### UPDATE
PUT http://localhost:8080/api/v1/region/1
Content-Type: application/json

{
  "orderNumber": 2,
  "nameUz": "Yangilangan Toshkent",
  "nameRu": "Обновленный Ташкент",
  "nameEn": "Updated Tashkent",
  "key": "updated-tashkent",
  "visible": false
}


### GET BY ID
GET http://localhost:8080/api/v1/region/1


### GET BY LANG
GET http://localhost:8080/api/v1/region/byLang?lang=UZ


### DELETE
DELETE http://localhost:8080/api/v1/region/1


### GET ALL
GET http://localhost:8080/api/v1/region/list
